### PR TITLE
check PR

### PR DESCRIPTION
**Pull request by GaganDureja**
just checking PR notification

### CODE REVIEW

**Comment by grsahil20** [comment]
You can delete or close this PR. 

and then create another one with correct commits

**Comment by grsahil20** [comment]
I cannot review 180 files in one go. Create PR's with small `< 20 files`

**Comment by GaganDureja** [comment]
> You can delete or close this PR.
> 
> and then create another one with correct commits

okay

**Comment by GaganDureja** [comment]
> I cannot review 180 files in one go. Create PR's with small `< 20 files`

yes I know they are just template files for design as written in commit

**Comment by grsahil20** [comment]
Lastly we don't need super fancy CSS or JS yet. 

One HTML with simple css and centre aligned form is good enough. 
Don't add unnecessary things.

**Comment by GaganDureja** [comment]
> Lastly we don't need super fancy CSS or JS yet.
> 
> One HTML with simple css and centre aligned form is good enough. Don't add unnecessary things.
> 
> okay I'll remove them and add simple bootstrap cdn

**Pull request closed without merging**
