### PR TITLE
postgresql dependency package (psycopg2) added

### PR DESCRIPTION
**Pull request by GaganDureja**
project causing error due to incomplete requirement of python module (psycopg2 )

### CODE REVIEW

**Comment by grsahil20** [comment]
This is not installing postgresql 

wrong name for commit and PR name

**Comment by GaganDureja** [comment]
> This is not installing postgresql
> 
> wrong name for commit and PR name

psycopg is used to connect db postgresql, so done like this. commit -> psycopg requirement added (is this ok?)

**Comment by grsahil20** [comment]
Change the commit too. 

Add dependendeny package_name to connect with postgres

**Comment by GaganDureja** [comment]
> Change the commit too.
> 
> Add dependendeny package_name to connect with postgres

commit and pull request changed

**Review by grsahil20 — APPROVED** [review]

**Pull request merged**
