### PR TITLE
unused column removed from user model

### PR DESCRIPTION
**Pull request by GaganDureja**
phone, verified account , profile image, background image and followers column removed.

### CODE REVIEW

**Comment by grsahil20** [comment]
migration to remove these columns from DB ?

**Comment by GaganDureja** [comment]
> migration to remove these columns from DB ?

Its done automatically we dont have to update it manually as its done now. But this is updating some pyc file also. I dont know its complusary or what but I uploaded all that changes.

**Comment by grsahil20** [comment]
> > migration to remove these columns from DB ?
> 
> Its done automatically we dont have to update it manually as its done now. But this is updating some pyc file also. I dont know its complusary or what but I uploaded all that changes.

Now I see migrations have been added. I see pyc files again ? Are those needed ?

**Comment by grsahil20** [comment]
what does 

> migration done ....
Done refers to what ? Use proper verbs added/deleted/removed/updated

**Comment by GaganDureja** [comment]
> > > migration to remove these columns from DB ?
> > 
> > 
> > Its done automatically we dont have to update it manually as its done now. But this is updating some pyc file also. I dont know its complusary or what but I uploaded all that changes.
> 
> Now I see migrations have been added. I see pyc files again ? Are those needed ?

Not needed, I've added the gitignore file to ignore all pyc files but its not doing in that so I let that upload.

**Comment by GaganDureja** [comment]
> what does
> 
> > migration done ....
> > Done refers to what ? Use proper verbs added/deleted/removed/updated

got it, updated commit now

**Comment by grsahil20** [comment]
> Not needed, I've added the gitignore file to ignore all pyc files but its not doing in that so I let that upload.

If you don't know how to fix a problem, don't ignore it. 

add  `**/**.pyc` to `gitignore`

**Comment by grsahil20** [comment]
After running the migration I see the following 

screenshot-2024-04-20_at_20 21 41@2x

we don't need 
- `username` 
- `is_superuser` 
- `is_staff`

**Comment by GaganDureja** [comment]
> After running the migration I see the following
> 
> screenshot-2024-04-20_at_20 21 41@2x
> 
> we don't need
> 
> * `username`
> * `is_superuser`
> * `is_staff`

these are automatically added when we start a django project. also the username is used to login without that I need to modify the login process as once done if you remember (login with email/mobile/username).

is_superuser is basically to differ from admin without that anyone can login to admin panel or can lead to error in admin panel

is_staff may be removed need to check that as these are not defined by me.

**Comment by GaganDureja** [comment]
> > Not needed, I've added the gitignore file to ignore all pyc files but its not doing in that so I let that upload.
> 
> If you don't know how to fix a problem, don't ignore it.
> 
> add `**/**.pyc` to `gitignore`

okay

**Comment by grsahil20** [comment]
why still .pyc files ?

**Pull request merged**
