### PR TITLE
converted from bootstrap to simple html page layout

### PR DESCRIPTION
**Pull request by GaganDureja**
Bootstrap cdn removed and sweetalert changed to simple message

### CODE REVIEW

**Comment by grsahil20** [comment]
whats bs ?

**Comment by grsahil20** [comment]
screenshot-2024-04-10_at_21 15 27@2x
- Change the commit too
- Check how to ammend a commit

**Comment by grsahil20** [comment]
Update PR description too 

screenshot-2024-04-10_at_21 15 53@2x

**Comment by GaganDureja** [comment]
commit and pull request name updated

**Comment by GaganDureja** [comment]
Closed

**Pull request closed without merging**
